# Generated by Django 5.1.1 on 2024-12-18 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_project_folder_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetestimate',
            name='format_type',
            field=models.CharField(choices=[('WEB', 'Web'), ('XLSX', 'Excel')], default='WEB', max_length=4, verbose_name='Format'),
        ),
        migrations.CreateModel(
            name='ProjectBudgetXLSX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_items', models.JSONField(default=list, verbose_name='Cost Items')),
                ('value_items', models.JSONField(default=list, verbose_name='Value Items')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Cost')),
                ('total_budget', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Budget')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xlxs_data', to='customer.budgetestimate')),
            ],
        ),
    ]
