# Generated by Django 5.1.1 on 2024-12-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_budgetestimate_format_type_projectbudgetxlsx'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectbudgetxlsx',
            name='xlsx_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Folder ID'),
        ),
    ]
