# Generated by Django 5.1.1 on 2025-01-14 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_projectbudgetxlsx_xlsx_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetestimatematerialdata',
            name='id_generated_by_checklist',
            field=models.CharField(default='Null', max_length=50),
        ),
        migrations.AddField(
            model_name='budgetestimatematerialdata',
            name='is_generated_by_checklist',
            field=models.BooleanField(default=False),
        ),
    ]
