# Generated by Django 5.1.1 on 2025-01-15 07:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_budgetestimatematerialdata_id_generated_by_checklist_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.CharField(max_length=255)),
                ('proposalInfo', models.JSONField(blank=True, default=dict)),
                ('project_name', models.CharField(default='none', max_length=255)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Created')),
                ('due_date', models.DateTimeField(verbose_name='Due Date')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Subtotal')),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Tax')),
                ('retention', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Retention')),
                ('total_proposal', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Invoice')),
                ('approved_by', models.CharField(blank=True, max_length=255, null=True)),
                ('print_name', models.CharField(blank=True, max_length=255, null=True)),
                ('signature', models.CharField(blank=True, max_length=255, null=True)),
                ('terms_conditions', models.TextField(blank=True, null=True, verbose_name='Terms and Conditions')),
                ('status', models.CharField(choices=[('new', 'New'), ('sent', 'Sent'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='new', max_length=20, verbose_name='Status')),
                ('budget', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='customer.budgetestimate')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='customer.project')),
                ('sales_advisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Sales Advisor')),
            ],
            options={
                'verbose_name': 'Proposal',
                'verbose_name_plural': 'Proposals',
            },
        ),
    ]
