# Generated by Django 5.1.1 on 2025-01-15 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_proposalprojects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalprojects',
            name='budget',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='customer.budgetestimate'),
        ),
    ]
