# Generated by Django 5.1.1 on 2025-01-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_alter_proposalprojects_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalprojects',
            name='billed_proposal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Billed'),
        ),
        migrations.AlterField(
            model_name='proposalprojects',
            name='total_proposal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Proposal'),
        ),
    ]
