# Generated by Django 5.1.1 on 2025-01-16 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_invoiceprojects_proposal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceprojects',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='invoiceprojects',
            name='print_name',
        ),
        migrations.RemoveField(
            model_name='invoiceprojects',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='invoiceprojects',
            name='signature',
        ),
        migrations.RemoveField(
            model_name='invoiceprojects',
            name='terms_conditions',
        ),
        migrations.RemoveField(
            model_name='invoiceprojects',
            name='tracking_id',
        ),
        migrations.AddField(
            model_name='invoiceprojects',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Invoice Paid'),
        ),
        migrations.AlterField(
            model_name='invoiceprojects',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='sent', max_length=20, verbose_name='Status'),
        ),
    ]
