# Generated by Django 5.1.1 on 2025-01-16 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_remove_invoiceprojects_approved_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceprojects',
            name='due_date',
        ),
        migrations.AddField(
            model_name='invoiceprojects',
            name='type_invoice',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
