# Generated by Django 5.1.1 on 2025-01-16 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_remove_invoiceprojects_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceprojects',
            name='due_date',
            field=models.DateTimeField(null=True, verbose_name='Due Date'),
        ),
    ]
