# Generated by Django 5.1.1 on 2025-01-16 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_invoiceprojects_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceprojects',
            name='proposal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='customer.proposalprojects'),
        ),
    ]
