# Generated by Django 5.1.1 on 2025-01-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_alter_invoiceprojects_proposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetestimate',
            name='isChangeOrder',
            field=models.BooleanField(default=False),
        ),
    ]
