# Generated by Django 5.1.1 on 2025-01-20 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_budgetestimate_ischangeorder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_manager_projects', to=settings.AUTH_USER_MODEL, verbose_name='Project Manager'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sales_advisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_advisor_projects', to=settings.AUTH_USER_MODEL, verbose_name='Sales Advisor'),
        ),
    ]
