# Generated by Django 5.1.1 on 2025-01-20 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_project_project_manager_alter_project_sales_advisor'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('progress', models.FloatField(default=0.0)),
                ('gantt_data', models.JSONField(default=list)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='customer.project')),
            ],
        ),
    ]
