# Generated by Django 5.1.1 on 2025-01-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0017_remove_taskproject_end_date_remove_taskproject_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetestimateutil',
            name='add_post_and_hole',
            field=models.BooleanField(default=False),
        ),
    ]
