# Generated by Django 5.1.1 on 2025-01-28 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_budgetestimateutil_add_post_and_hole'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetestimate',
            name='dataPreview',
            field=models.JSONField(default=list),
        ),
    ]
