# Generated by Django 5.1.1 on 2025-02-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0019_budgetestimate_datapreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetestimate',
            name='dataPreview',
            field=models.JSONField(default=list, null=True),
        ),
    ]
