# Generated by Django 5.1.1 on 2025-02-04 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0020_alter_budgetestimate_datapreview'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='project',
            table='Project',
        ),
    ]
