# Generated by Django 5.1.1 on 2025-02-04 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0021_alter_project_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='project',
            table=None,
        ),
    ]
