# Generated by Django 5.1.1 on 2025-02-06 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0023_realcostproject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realcostproject',
            old_name='subitems',
            new_name='items',
        ),
    ]
