# Generated by Django 5.1.1 on 2025-02-20 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0025_role_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetestimateutil',
            name='total_ft',
        ),
        migrations.RemoveField(
            model_name='budgetestimateutil',
            name='total_posts',
        ),
        migrations.AddField(
            model_name='budgetestimateutil',
            name='totalFtAdPost',
            field=models.JSONField(default=list, null=True),
        ),
    ]
