# Generated by Django 5.1.1 on 2025-04-09 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('customer', '0027_remove_budgetestimateutil_hole_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Creación'), ('UPDATE', 'Actualización'), ('DELETE', 'Eliminación'), ('STATUS_CHANGE', 'Cambio de Estado'), ('BUDGET_CHANGE', 'Cambio de Presupuesto'), ('PROPOSAL_CHANGE', 'Cambio de Propuesta'), ('INVOICE_CHANGE', 'Cambio de Factura'), ('COMMENT', 'Comentario'), ('OTHER', 'Otro')], max_length=20, verbose_name='Acción')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='Cambios')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='customer.project', verbose_name='Proyecto')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.user', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Historial de Proyecto',
                'verbose_name_plural': 'Historial de Proyectos',
                'ordering': ['-timestamp'],
            },
        ),
    ]
