# Generated by Django 5.1.1 on 2025-04-10 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0028_projecthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalprojects',
            name='exclusions',
            field=models.TextField(blank=True, default='Permit Fee and processing, Site survey, Electrical fence grounding', null=True, verbose_name='Exclusions'),
        ),
    ]
