# Generated by Django 5.1.1 on 2025-04-11 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0030_proposalprojects_scope_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetestimateutil',
            name='margin_error_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='budgetestimateutil',
            name='percentage_margin_error',
            field=models.IntegerField(default=5),
        ),
    ]
