# Generated by Django 5.1.1 on 2025-04-28 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0031_budgetestimateutil_margin_error_check_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='customer.customer', verbose_name='Customer'),
        ),
    ]
