# Generated by Django 5.1.1 on 2025-05-02 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0033_alter_project_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecthistory',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='customer.project', verbose_name='Proyecto'),
        ),
    ]
