# Generated by Django 5.1.1 on 2025-05-02 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0034_alter_projecthistory_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecthistory',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='customer.project', verbose_name='Proyecto'),
        ),
    ]
