# Generated by Django 5.1.1 on 2025-06-23 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0037_alter_projecthistory_user_remove_role_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
