# Generated by Django 5.1.1 on 2025-06-23 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0038_delete_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('quote_sent', 'Quote Sent'), ('in_negotiation', 'In Negotiation'), ('approved', 'Approved'), ('not_approved', 'Not Approved'), ('in_planning', 'Planning and Documentation'), ('in_design', 'In Installation'), ('in_production', 'In Production'), ('pending_payment', 'Pending Payment'), ('inactive', 'Inactive'), ('cancelled', 'Cancelled')], default='new', max_length=20, verbose_name='Status'),
        ),
    ]
