# Generated by Django 5.1.1 on 2025-06-24 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0043_commentsproject_mentioned_users_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentsproject',
            name='mentioned_users',
        ),
        migrations.RemoveField(
            model_name='commentsproject',
            name='parent_comment',
        ),
    ]
