# Generated by Django 5.1.1 on 2025-06-24 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0046_commentsproject_is_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentsproject',
            name='is_reply',
        ),
    ]
