# Generated by Django 5.1.1 on 2025-06-24 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0047_remove_commentsproject_is_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecthistory',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Creation'), ('UPDATE', 'Update'), ('DELETE', 'Deletion'), ('STATUS_CHANGE', 'Status Change'), ('BUDGET_CHANGE', 'Budget Change'), ('PROPOSAL_CHANGE', 'Proposal Change'), ('INVOICE_CHANGE', 'Invoice Change'), ('COMMENT', 'Comment'), ('OTHER', 'Other')], max_length=20, verbose_name='Acción'),
        ),
    ]
