# Generated by Django 5.1.1 on 2025-06-26 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0050_customer_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('mention', 'Mention'), ('reply', 'Reply'), ('project_update', 'Project Update'), ('status_change', 'Status Change'), ('manager_assignment', 'Manager Assignment')], max_length=20),
        ),
    ]
