# Generated by Django 5.1.1 on 2025-07-01 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0051_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='accounting_cost_request',
            field=models.CharField(blank=True, choices=[('GLOBAL COST REQUEST', 'GLOBAL COST REQUEST'), ('ITEM COST REQUEST', 'ITEM COST REQUEST')], default=None, max_length=50, null=True, verbose_name='Accounting Cost Request'),
        ),
    ]
