# Generated by Django 5.1.1 on 2025-07-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0052_project_accounting_cost_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='production_funding_request',
            field=models.CharField(blank=True, choices=[('GLOBAL COST REQUEST', 'GLOBAL COST REQUEST'), ('ITEM COST REQUEST', 'ITEM COST REQUEST')], default=None, max_length=50, null=True, verbose_name='Production Funding Request'),
        ),
    ]
