# Generated by Django 5.1.1 on 2025-07-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0054_project_evidence_required_productionfundingrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionfundingrequest',
            name='cost_request_type',
            field=models.CharField(blank=True, choices=[('GLOBAL COST REQUEST', 'GLOBAL COST REQUEST'), ('ITEM COST REQUEST', 'ITEM COST REQUEST')], max_length=50, null=True, verbose_name='Cost Request Type'),
        ),
    ]
