# Generated by Django 5.1.1 on 2025-07-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0055_productionfundingrequest_cost_request_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='evidence_required',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
