# Generated by Django 5.1.1 on 2025-07-04 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0056_alter_project_evidence_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='realcostproject',
            name='evidence_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
