# Generated by Django 5.1.1 on 2025-07-08 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0058_productionchangelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='production_closed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
