# Generated by Django 5.1.1 on 2025-07-08 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0059_project_production_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='production_closed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Production Closed Date'),
        ),
    ]
