# Generated by Django 5.1.1 on 2025-07-09 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0060_project_production_closed_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentsreceived',
            old_name='data_receipt',
            new_name='url_receipt',
        ),
        migrations.RemoveField(
            model_name='paymentsreceived',
            name='account',
        ),
        migrations.RemoveField(
            model_name='paymentsreceived',
            name='additional_info',
        ),
        migrations.RemoveField(
            model_name='paymentsreceived',
            name='is_receipt',
        ),
    ]
