# Generated by Django 5.1.1 on 2025-07-10 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0061_rename_data_receipt_paymentsreceived_url_receipt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.CharField(max_length=100, unique=True)),
                ('project_id', models.IntegerField(blank=True, null=True)),
                ('proposal_id', models.IntegerField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('last_opened_at', models.DateTimeField(blank=True, null=True)),
                ('opened_count', models.IntegerField(default=1)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Email Tracking',
                'verbose_name_plural': 'Email Tracking',
                'db_table': 'email_tracking',
            },
        ),
    ]
