# Generated by Django 5.1.1 on 2025-07-10 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0062_emailtracking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailTracking',
        ),
    ]
