# Generated by Django 5.1.1 on 2025-07-13 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0063_delete_emailtracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.CharField(max_length=255, unique=True, verbose_name='Tracking ID')),
                ('email_type', models.CharField(choices=[('proposal', 'Proposal'), ('invoice', 'Invoice'), ('notification', 'Notification'), ('other', 'Other')], max_length=20, verbose_name='Email Type')),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='Recipient Email')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Sent At')),
                ('opened_at', models.DateTimeField(blank=True, null=True, verbose_name='Opened At')),
                ('opened_count', models.PositiveIntegerField(default=0, verbose_name='Times Opened')),
                ('last_opened_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Opened At')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Additional Data')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.invoiceprojects', verbose_name='Invoice')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.project', verbose_name='Project')),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.proposalprojects', verbose_name='Proposal')),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Sent By')),
            ],
            options={
                'verbose_name': 'Email Tracking',
                'verbose_name_plural': 'Email Tracking',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['tracking_id'], name='customer_em_trackin_b123aa_idx'), models.Index(fields=['email_type'], name='customer_em_email_t_7c7b2f_idx'), models.Index(fields=['sent_at'], name='customer_em_sent_at_5edb05_idx')],
            },
        ),
    ]
