# Generated by Django 5.1.1 on 2025-07-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0064_emailtracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtracking',
            name='sender_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Sender IP'),
        ),
    ]
