# Generated by Django 5.1.1 on 2025-07-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0065_emailtracking_sender_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtracking',
            name='sender_ip',
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('quote_sent', 'Quote Sent'), ('in_negotiation', 'In Negotiation'), ('approved', 'Approved'), ('not_approved', 'Not Approved'), ('planning_and_documentation', 'Planning and Documentation'), ('in_accounting', 'In Accounting'), ('in_production', 'In Production'), ('pending_payment', 'Pending Payment'), ('inactive', 'Inactive'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='new', max_length=30, verbose_name='Status'),
        ),
    ]
