# Generated by Django 5.1.1 on 2025-07-15 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0066_remove_emailtracking_sender_ip_alter_project_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeOrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_contract_no', models.CharField(blank=True, max_length=50, null=True)),
                ('job_location', models.CharField(blank=True, max_length=255, null=True)),
                ('purchase_order', models.CharField(blank=True, max_length=50, null=True)),
                ('existing_contract_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('change_order_no', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='change_order_detail', to='customer.budgetestimate')),
            ],
        ),
        migrations.CreateModel(
            name='ChangeOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('change_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='customer.changeorderdetail')),
            ],
        ),
    ]
