# Generated by Django 5.1.1 on 2025-08-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0069_project_collaborators_projectcollaborationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeorderdetail',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20, verbose_name='Status'),
        ),
    ]
