# Generated by Django 5.1.1 on 2025-05-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_alter_account_options_alter_auditlog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='code',
            field=models.CharField(choices=[('1000', 'Cash'), ('1100', 'Accounts Receivable'), ('2000', 'Accounts Payable'), ('3000', 'Common Stock'), ('4000', 'Sales Revenue'), ('5000', 'Cost of Goods Sold')], default=1, max_length=10, unique=True, verbose_name='Account Code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='initial_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Initial Balance'),
        ),
    ]
