# Generated by Django 5.1.1 on 2025-05-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_alter_account_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.CharField(choices=[('1000', 'Cash'), ('1100', 'Accounts Receivable'), ('2000', 'Accounts Payable'), ('3000', 'Common Stock'), ('4000', 'Sales Revenue'), ('5000', 'Cost of Goods Sold')], max_length=10, unique=True, verbose_name='Account Code'),
        ),
    ]
