# Generated by Django 5.1.1 on 2025-05-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_alter_account_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='code',
        ),
        migrations.AddField(
            model_name='account',
            name='account_code',
            field=models.IntegerField(default=0, verbose_name='Account Code'),
        ),
        migrations.AddField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='account',
            name='sub_subaccount_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sub-Subaccount Code'),
        ),
        migrations.AddField(
            model_name='account',
            name='subaccount_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Subaccount Code'),
        ),
    ]
