# Generated by Django 5.1.1 on 2025-05-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_remove_account_code_account_account_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='type_element',
            field=models.CharField(choices=[('ACCOUNT', 'Account'), ('SUBACCOUNT', 'Subaccount'), ('SUB-SUBACCOUNT', 'Sub-Subaccount')], default='ACCOUNT', max_length=20, verbose_name='Type Element'),
        ),
    ]
