# Generated by Django 5.1.1 on 2025-05-09 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_account_parent_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='type_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Type ID'),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('EQUITY', 'Equity'), ('INCOME', 'Income'), ('EXPENSE', 'Expense'), ('OTHER', 'Other'), ('INTERCOMPANY', 'Intercompany'), ('OTHERS_EXPENSES_INCOME', 'Others Expenses Income')], max_length=50, verbose_name='Account Type'),
        ),
    ]
