# Generated by Django 5.1.1 on 2025-05-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_account_type_id_alter_account_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='group_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Group Code'),
        ),
        migrations.AddField(
            model_name='account',
            name='item_group_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Item Group Code'),
        ),
        migrations.AddField(
            model_name='account',
            name='sub_group_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sub-Group Code'),
        ),
    ]
