# Generated by Django 5.1.1 on 2025-05-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_account_group_code_account_item_group_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='item_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Item Code'),
        ),
        migrations.AlterField(
            model_name='account',
            name='type_element',
            field=models.CharField(choices=[('ACCOUNT', 'Account'), ('SUBACCOUNT', 'Subaccount'), ('SUB-SUBACCOUNT', 'Sub-Subaccount'), ('GROUP', 'Group'), ('SUBGROUP', 'Subgroup'), ('ITEMGROUP', 'Itemgroup'), ('ITEM', 'Item')], default='ACCOUNT', max_length=20, verbose_name='Type Element'),
        ),
    ]
