# Generated by Django 5.1.1 on 2025-05-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_account_item_code_alter_account_type_element'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_created_by_user',
            field=models.BooleanField(default=False, verbose_name='Is Created By User'),
        ),
    ]
