# Generated by Django 5.1.1 on 2025-06-22 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_account_is_created_by_user'),
        ('customer', '0035_alter_projecthistory_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='customer.invoiceprojects', verbose_name='Invoice'),
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
